/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseContainer: typeof import('./src/layouts/BaseContainer.vue')['default']
    MainLayout: typeof import('./src/layouts/MainLayout.vue')['default']
    NavigationMenuDemoItem: typeof import('./src/layouts/NavigationMenuDemoItem.vue')['default']
    NavigationMenuLink: typeof import('./src/layouts/NavigationMenuLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/layouts/TheFooter.vue')['default']
    TheNavigation: typeof import('./src/layouts/TheNavigation.vue')['default']
  }
}
